fix(safe-claiming-app): validate custom delegation address
safe-global/safe-react-apps pull request #541
Opened 2022-10-04 09:32 UTC by usame-algan

## What it solves
Resolves #540 

## How this PR fixes it

- Updates the input field text description
- Validates that the address is not the same as the current safe address

## How to test it

1. Open a safe that is elligible for the airdrop
2. Navigate to the custom delegate screen
3. Input the current safe address
4. Observe a validation error and the next button is disabled
5. Input an ENS that resolves to the current safe address
6. Observe a validation error and the next button is disabled 

## Screenshots
<img width="688" alt="Screenshot 2022-10-04 at 11 31 55" src="https://user-images.githubusercontent.com/5880855/193785853-08bc9031-1883-4f3f-abfc-dff6bec9da24.png">

2022-10-04 12:52 UTC, DiogoSoaress requested changes

2022-10-04 12:52 UTC, DiogoSoaress commented on apps/safe-claiming-app/src/hooks/useEnsResolution.ts
> +          if (resolvedName === safe.safeAddress) {
`sameAddress` is safer perhaps

2022-10-04 13:07 UTC, DiogoSoaress approved these changes

2022-10-05 08:39 UTC, schmanu requested changes
The changes look 👀  good.

But there is a unit test for the `useEnsResolution` hook. 
You should add the 2 new created cases there: 
- address is safe address
- ens name resolves to safe address

2022-10-05 08:59 UTC, schmanu approved these changes
Perfect! Nice fix!

2022-10-05 09:12 UTC, merged

2022-10-05 10:25 UTC, liliya-soroka commented
Verified